// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJp0x6zSqBYGs9fgeR0JiOUuJ2amCakIw',
    appId: '1:16186092618:web:c530082071bf9b2a504ab3',
    messagingSenderId: '16186092618',
    projectId: 'tamagotchu-80dd2',
    authDomain: 'tamagotchu-80dd2.firebaseapp.com',
    databaseURL: 'https://tamagotchu-80dd2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tamagotchu-80dd2.firebasestorage.app',
    measurementId: 'G-P5L77F14W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg081qI8HRXL0Z2K1BdQDySGVggFAlMeQ',
    appId: '1:16186092618:android:09ad6c8638891cca504ab3',
    messagingSenderId: '16186092618',
    projectId: 'tamagotchu-80dd2',
    databaseURL: 'https://tamagotchu-80dd2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tamagotchu-80dd2.firebasestorage.app',
  );
}
